<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Notifications\DatabaseNotification;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

use App\Models\Dream;
use App\Models\Avatar;
use App\Models\Like;
use App\Models\Comment;
use App\Models\Conversation;
use App\Models\Message;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'recovery_email', // custom field
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
        'dream_tokens' => 'array',
        'avatar_config' => 'array',
    ];

    /**
     * Get all dreams submitted by the user.
     */
    public function dreams(): HasMany
    {
        return $this->hasMany(Dream::class);
    }

    /**
     * Get all avatars generated by the user.
     */
    public function avatars(): HasMany
    {
        return $this->hasMany(Avatar::class);
    }

    public function likes(): HasMany
    {
        return $this->hasMany(Like::class);
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    /**
     * Get the notifications for the user (optional but useful).
     */
    public function notifications()
    {
        return $this->morphMany(DatabaseNotification::class, 'notifiable');
    }

    /**
     * 🔗 Conversations this user participates in (for chat).
     */
    public function conversations(): BelongsToMany
    {
        // Uses the pivot table conversation_user by convention
        return $this->belongsToMany(Conversation::class)->withTimestamps();
    }

    /**
     * ✉️ Messages this user has sent (for chat).
     */
    public function messages(): HasMany
    {
        return $this->hasMany(Message::class);
    }
}
